---
- name: Ensure user accounts are present.
  user:
    name: "{{ item.name | default(item) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    createhome: true
    groups: "{{ item.groups | default(omit) }}"
    home: /home/{{ item.name | default(item) }}
    state: present
  with_items: "{{ users }}"

- name: Ensure authorized_keys for user accounts are present.
  authorized_key:
    user: "{{ item.name | default(item) }}"
    key: "{{ github_url }}/{{ item.github_username | default(item) }}.keys"
    manage_dir: true
    exclusive: "{{ users_authorized_keys_exclusive }}"
  with_items: "{{ users }}"

- name: Ensure user accounts in users_absent are absent.
  user:
    name: "{{ item.name | default(item) }}"
    state: absent
  with_items: "{{ users_absent }}"
