---
- name: re-configure voctomix
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/voctomix/{{ item }}"
  with_items:
  - voctocore.ini

- name: remove voctogui autostart
  file:
    path: /etc/xdg/autostart/voctogui.desktop
    state: absent

