---
- hosts: onsite
- hosts: storage-key-client
  roles:
    - storage-key-client
- hosts: storage-server
  roles:
    - storage-key-server
    - storage-volume
    - storage-nfs-server
- hosts: meetupsencoder-orchestrator
  roles:
    - squid-deb-docker-acl
    - geerlingguy.docker
    - docker-py
    - encoder-orchestrator
- hosts: meetupsencoder-worker
  roles:
    - squid-deb-docker-acl
    - geerlingguy.docker
    - docker-py
    - encoder-worker
- hosts: tftp-dhcp-additions
  roles:
    - dns-for-static-hosts
- hosts: voctomix-overrides
  roles:
    - voctomix-overrides
