---
- hosts: onsite
# - hosts: '*'
#   roles:
#   - apt
#   - system-software
#   - users

# - hosts: tftp-dhcp-server
#   roles:
#   - dhcp-server
#   - tftp-server
#   - squid-deb-proxy

# - hosts: nfs-server
#   roles:
#   - nfs-server

# - hosts: onsite
#   roles:
#   - bash
#   - motd
#   - staticips

# - hosts: opsis
#   roles:
#   - opsis
#   - opsis-ingest

# - hosts: voctomix
#   roles:
#   - xorg
#   - voctomix
#   - blackmagic
#   - vim

# - hosts: xorg
#   roles:
#   - xorg

# - hosts: test-station
#   roles:
#   - xorg
#   - opsis
#   - test-station

#   # everything on one box
#   # secrets copied from ansible master
# - hosts: veyepar-basic
#   roles:
#   - veyepar-code
#   - veyepar-deps
#   - veyepar-local-assets
#   - veyepar-secrets

#   # veyepar, secrets, assets on nfs server
#   # dependences installed locally
# - hosts: veyepar-encoder-nfs-storage
#   roles:
#   - nfs-client
#   - veyepar-deps

# - hosts: encoder
#   roles:
#   - nfs-client
#   - gridengine-exec
#   - sreview

# - hosts: review
#   roles:
#   - xorg

# - hosts: ge-master
#   roles:
#   - gridengine-master
#   - gridengine-config
#   - gridengine-exec
#   - sreview
#   - sreview-master

# - hosts: streaming-backends
#   roles:
#   - streaming-backend

# - hosts: streaming-frontends
#   roles:
#   - streaming-frontend
