---
- name: fish config directories
  file:
    state: directory
    path: "{{patrick_interactive_home}}/{{item}}"
    mode: "0755"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - ".config/fish"
  - ".config/fish/functions"
  - ".config/fish/completions"
  - ".config/fisherman"

- name: fish.config
  template:
    src: "templates/config.fish.j2"
    dest: "{{patrick_interactive_home}}/.config/fish/config.fish"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"

- name: fish config files
  copy:
    src: "files/{{item}}"
    dest: "{{patrick_interactive_home}}/.config/fish/{{item}}"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - "fish_variables"
  - "fishfile"
  - "shell_prompt.sh"
  - "completions/fisher.fish"
  - "functions/copy-bass.fish"
  - "functions/fish_prompt.fish"
  - "functions/fisher.fish"
  - "functions/rvm.fish"

- name: get bass
  git:
    repo: https://github.com/edc/bass
    dest: "{{patrick_interactive_home}}/.config/fisherman/bass"
  become: yes
  become_user: "{{patrick_interactive_user}}"

- name: Link bass
  file:
    state: link
    src: "{{patrick_interactive_home}}/.config/fisherman/bass/functions/{{item}}"
    dest: "{{patrick_interactive_home}}/.config/fish/functions/{{item}}"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - "__bass.py"
  - "bass.fish"

- name: "vimrc"
  copy:
    src: "files/vimrc"
    dest: "{{patrick_interactive_home}}/.vimrc"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"

