---
- name: home directory directories
  file:
    state: directory
    path: "{{patrick_interactive_home}}/{{item}}"
    mode: "0755"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - "bin"

