---
- name: nvm
  become: "yes"
  become_user: "{{patrick_interactive_user}}"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: "{{ patrick_interactive_home }}/.nvm/nvm.sh"
    warn: false

- name: nvm install helper
  become: "yes"
  become_user: "{{patrick_interactive_user}}"
  template:
    src: "templates/nvm-install-version.sh.j2"
    dest: "{{patrick_interactive_home}}/.nvm/install-helper.sh"
    mode: "0755"

- name: node v16.3.0
  become: "yes"
  become_user: "{{patrick_interactive_user}}"
  shell: >
    {{patrick_interactive_home}}/.nvm/install-helper.sh v16.3.0
  args:
    creates: "{{patrick_interactive_user}}/versions/node/v16.3.0/node"
