---
- name: ssh directories
  file:
    state: directory
    path: "{{patrick_interactive_home}}/{{item}}"
    mode: "0755"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - ".ssh"
  - ".ssh/tmp"

- name: ssh config
  template:
    src: "templates/ssh/config.j2"
    dest: "{{patrick_interactive_home}}/.ssh/config"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"

- name: download diff-so-fancy
  get_url:
    url: https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.4/diff-so-fancy
    # https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: "{{patrick_interactive_home}}/bin/diff-so-fancy"
    mode: "0755"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"

