---
- name: ssh directories
  file:
    state: directory
    path: "/home/patrick/{{item}}"
    mode: "0755"
    owner: "patrick"
    group: "patrick"
  with_items:
  - ".ssh"
  - ".ssh/tmp"

- name: ssh config
  template:
    src: "templates/ssh/config.j2"
    dest: "/home/patrick/.ssh/config"
    owner: "patrick"
    group: "patrick"

- name: download diff-so-fancy
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: "/home/patrick/bin/diff-so-fancy"
    mode: "0755"
    owner: "patrick"
    group: "patrick"

