---
- name: vim config directories
  file:
    state: directory
    path: "/home/patrick/{{item}}"
    mode: "0755"
    owner: "patrick"
    group: "patrick"
  with_items:
  - ".vim"
  - ".vim/autoload"
  - ".vim/bundle"
  - ".vim/colors"

- name: "vimrc"
  copy:
    src: "files/vimrc"
    dest: "/home/patrick/.vimrc"
    owner: "patrick"
    group: "patrick"

- name: vim config files
  copy:
    src: "files/vim/{{item}}"
    dest: "/home/patrick/.vim/{{item}}"
    owner: "patrick"
    group: "patrick"
  with_items:
  - "autoload/pathogen.vim"
  - "colors/onedark.vim"

- name: get bass
  git:
    repo: "https://github.com/{{item.repo}}.git"
    dest: "/home/patrick/.vim/bundle/{{item.name}}"
  become: "yes"
  become_user: "patrick"
  loop:
  - name: 'command-t'
    repo: 'wincent/command-t'
  - name: 'vim-airline'
    repo: 'bling/vim-airline'
  - name: 'syntastic'
    repo: 'scrooloose/syntastic'
  - name: 'nerdtree'
    repo: 'scrooloose/nerdtree'
  - name: 'swift'
    repo: 'Keithbsmiley/swift.vim'
  - name: 'vim-unimpaired'
    repo: 'tpope/vim-unimpaired'
  - name: 'Dockerfile'
    repo: 'ekalinin/Dockerfile.vim'
  - name: 'promptline.vim'
    repo: 'edkolev/promptline.vim'

