---
- name: Ensure vim Is Present unless on macOS
  become: true
  become_user: "{{patrick_interactive_package_user}}"
  package:
    name: 'vim'
    state: present
  when: 'ansible_distribution != "MacOSX"'

- name: Ensure vim Is Present on macOS
  homebrew:
    name: vim
    path: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew/bin', '/usr/local/bin') }}"
    state: present
  become: true
  become_user: "{{patrick_interactive_package_user}}"
  when: ansible_distribution == "MacOSX"

- name: vim config directories
  file:
    state: directory
    path: "{{patrick_interactive_home}}/{{item}}"
    mode: "0755"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - ".vim"
  - ".vim/autoload"
  - ".vim/bundle"
  - ".vim/colors"

- name: "vimrc"
  copy:
    src: "files/vimrc"
    dest: "{{patrick_interactive_home}}/.vimrc"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"

- name: vim config files
  copy:
    src: "files/vim/{{item}}"
    dest: "{{patrick_interactive_home}}/.vim/{{item}}"
    owner: "{{patrick_interactive_user}}"
    group: "{{patrick_interactive_group}}"
  with_items:
  - "autoload/pathogen.vim"
  - "colors/onedark.vim"

- name: get bass
  git:
    repo: "https://github.com/{{item.repo}}.git"
    dest: "{{patrick_interactive_home}}/.vim/bundle/{{item.name}}"
  become: "yes"
  become_user: "{{patrick_interactive_user}}"
  loop:
  - name: 'command-t'
    repo: 'wincent/command-t'
  - name: 'vim-airline'
    repo: 'bling/vim-airline'
  - name: 'syntastic'
    repo: 'scrooloose/syntastic'
  - name: 'nerdtree'
    repo: 'scrooloose/nerdtree'
  - name: 'swift'
    repo: 'Keithbsmiley/swift.vim'
  - name: 'vim-unimpaired'
    repo: 'tpope/vim-unimpaired'
  - name: 'Dockerfile'
    repo: 'ekalinin/Dockerfile.vim'
  - name: 'promptline.vim'
    repo: 'edkolev/promptline.vim'
  - name: 'ale'
    repo: 'dense-analysis/ale'


