---
- hosts: common
  roles:
  - fish
  - users 
  - weareinteractive.sudo
  - ssh-lockdown
  - mosh
- hosts: ansible
  roles:
  - patrick-interactive
- hosts: argon
  roles:
  - patrick-interactive
  - geerlingguy.docker
- hosts: macs
  roles:
  - fish
  # - users 
  # - weareinteractive.sudo
  # - ssh-lockdown
  # - patrick-interactive
