---
- hosts: basics
  roles:
  - fish
  - role: users 
    tags: users
  - weareinteractive.sudo
  - ssh-lockdown

- hosts: servers
  roles:
  - mosh
  - patrick-interactive

- hosts: google-cloud-sdk
  roles:
  - google-cloud-sdk


- hosts: docker
  roles:
  - geerlingguy.docker
  - docker-py

- hosts: macs
  vars:
    fish_package_user: patrick
    patrick_interactive_home: /Users/patrick
    patrick_interactive_group: staff
    patrick_interactive_package_user: patrick
  roles:
  - fish
  - patrick-interactive
