---
- hosts: common
  roles:
  - fish
  - users 
  - weareinteractive.sudo
  - ssh-lockdown
  - mosh
- hosts: ansible
  roles:
  - patrick-interactive
- hosts: argon
  roles:
  - patrick-interactive
  - geerlingguy.docker

