eth_local_address: 10.18.0.3
eth_local_netmask: 24
eth_local_gateway:
# Change to reflect the MAC addresses of your gateway
eth_local_mac_address: 00:0e:c4:d0:56:aa
eth_uplink_mac_address: 00:0e:c4:d0:56:a9

# If you want to use a static IP for the uplink
eth_uplink_static: true
eth_uplink_static_address: 10.244.65.1
eth_uplink_static_netmask: 16
eth_uplink_static_gateway: 10.244.0.1
