---
room_name: standalone

irc_room_channel: "#thepatrick-cloud-video"
irc_nick: thepatrickcloud1

static_ip: 10.18.0.10

sources:
  - Camera1
  - Grabber

# To enable proprietary drivers, provide a URL to them.
blackmagic:
  urls:
    desktopvideo: http://gw/bm/desktopvideo_10.11.4a9_amd64.deb
    desktopvideo_gui: http://gw/bm/desktopvideo-gui_10.11.4a9_amd64.deb
  dkms_version: 10.11.4a9

blackmagic_sources:
  - card: 0
    connection: SDI
    audio: true
    mode: 15
# - card: 1
#  connection: SDI
#  audio: false
#  mode: 1080p60
# check the frequency setting on the camera
# make sure it matches what's the frequency of the local power
# use BlackmagicDesktopVideoSetup to see what the camera is sending
# 720p59.94 is 18
# 720p50 is 17
# list of all mode IDs: check 'gst-inspect-1.0 decklinkvideosrc'

# voctolights:
#   - camera: Cam1
#     plugin: serial_dtr
#     port: /dev/ttyUSB0

# serial_terminal:
# - tio
# - minicom
