---
  # To build this container
  # docker build -t thepatrick/webserver-caddy --build-arg plugins=cloudflare github.com/abiosoft/caddy-docker.git
  # docker build -t thepatrick/webserver-caddy --build-arg plugins=cloudflare,route53 github.com/abiosoft/caddy-docker.git
  # docker tag thepatrick/webserver-caddy:latest thepatrick/webserver-caddy:1.1.0
  # docker push thepatrick/webserver-caddy:1.1.0

- name: caddy folders
  file:
    state: directory
    path: "{{item}}"
    mode: "0755"
  with_items:
  - "/opt/thepatrick/webserver/"
  - "/opt/thepatrick/webserver/sites/"
  - "/opt/thepatrick/webserver/sites/notfound/"
  - "/opt/thepatrick/webserver/sites-enabled/"

- name: pull caddy container
  docker_image:
    name: thepatrick/webserver-caddy
    tag: 1.1.0

- name: write caddyfile
  copy:
    src: files/Caddyfile
    dest: /opt/thepatrick/webserver/Caddyfile
    mode: "0644"
  notify: reload thepatrick-webserver-caddy

- name: write websites
  copy:
    src: files/sites/{{item}}
    dest: /opt/thepatrick/webserver/sites-enabled/{{item}}
  notify: reload thepatrick-webserver-caddy
  with_items:
  - "thepatrick.cloud"
  - "twopats.live"

- name: write static websites
  copy:
    src: files/sites-files/{{item}}
    dest: /opt/thepatrick/webserver/sites/{{item}}
  notify: reload thepatrick-webserver-caddy
  with_items:
  - "notfound/index.html"

- name: run caddy container
  docker_container:
    name: thepatrick-webserver-caddy
    image: thepatrick/webserver-caddy:1.1.0
    state: started
    restart_policy: always
    command:
    - "--conf"
    - "/opt/thepatrick/webserver/Caddyfile"
    - "--log"
    - "stdout"
    - "--agree=true"
    - "--disable-http-challenge"
    - "--port"
    - "443"
    - "--http-port"
    - "80"
    env:
      ACME_AGREE: "true"
      CADDYPATH: "/opt/thepatrick/webserver/caddycerts"
      CLOUDFLARE_EMAIL: "{{thepatrick_cloudflare_email}}"
      CLOUDFLARE_API_KEY: "{{thepatrick_cloudflare_api_key}}"
      AWS_ACCESS_KEY_ID: "{{thepatrick_aws_caddy_key_id}}"
      AWS_SECRET_ACCESS_KEY: "{{thepatrick_aws_caddy_secret}}"
    volumes:
    - "/opt/thepatrick/webserver:/opt/thepatrick/webserver"
    published_ports:
    - "80:80"
    - "443:443"
    # links:
    #   - "meetupsencoder-redis:redis"
